# Generated by Django 3.2.6 on 2021-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='nieuwsweb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('listarticleobject', models.CharField(max_length=200)),
                ('listarticleelement', models.CharField(max_length=200)),
                ('listarticlename', models.CharField(max_length=200)),
                ('linkarticleobject', models.CharField(max_length=200)),
                ('linkarticleelement', models.CharField(max_length=200)),
                ('linkarticlename', models.CharField(max_length=200)),
                ('titlearticleobject', models.CharField(max_length=200)),
                ('titlearticleelement', models.CharField(max_length=200)),
                ('titlearticlename', models.CharField(max_length=200)),
                ('descarticleobject', models.CharField(blank=True, max_length=200)),
                ('descarticleelement', models.CharField(blank=True, max_length=200)),
                ('descearticlename', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
