# Generated by Django 3.2.6 on 2021-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211129_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
